(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> Invalid URI string in DAL"
p3
sS'layer'
p4
S'C:\\cygwin64\\home\\austi\\web2py\\applications\\Squish\\models\\db.py'
p5
sS'code'
p6
S'<code object <module> at 0ADBECC8, file "C:\\cygwin64\\home\\austi\\web2py\\applications\\Squish\\models\\db.py", line 7>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\cygwin64\\home\\austi\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\cygwin64\\home\\austi\\web2py\\applications\\Squish\\models\\db.py", line 28, in <module>\n    db = DAL(\'mysql://<squish>:<sQu1$Hadmin>@squish.mysql.pythonanywhere-services.com\')\n  File "C:\\cygwin64\\home\\austi\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 170, in __call__\n    obj = super(MetaDAL, cls).__call__(*args, **kwargs)\n  File "C:\\cygwin64\\home\\austi\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 455, in __init__\n    self._adapter = adapter(**kwargs)\n  File "C:\\cygwin64\\home\\austi\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\__init__.py", line 40, in __call__\n    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)\n  File "C:\\cygwin64\\home\\austi\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 369, in __init__\n    super(SQLAdapter, self).__init__(*args, **kwargs)\n  File "C:\\cygwin64\\home\\austi\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 51, in __init__\n    self._initialize_(do_connect)\n  File "C:\\cygwin64\\home\\austi\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\mysql.py", line 23, in _initialize_\n    raise SyntaxError("Invalid URI string in DAL")\nSyntaxError: Invalid URI string in DAL\n'
p11
s.